version: '3'

networks:
  rede:
    driver: bridge

volumes:
  database:

services:
  mdb:
    image: mongo:4.4.6
    volumes:
      - "database:/data/db"
    networks:
      - rede
    ports:
      - 27017:27017
    env_file:
      - .env
  todolist:
    image: oliveirafull/todolist:latest
    networks:
      - rede
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mdb
    
    
    